services:
  - type: web
    name: tweetster
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "myproject.settings"
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret
      - key: SECRET_KEY
        value: your_actual_secret_key_here
      - key: DATABASE_URL
        fromDatabase:
          name: tweetster-db
          property: connectionString
