# Generated by Django 4.2.21 on 2025-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.TextField(default='my first blog', max_length=240),
        ),
    ]
